# This is a basic workflow to help you get started with Actions

name: CI
name: Update Cloudflare Uniques

on:
  schedule:
    - cron: "20 5 * * *"   # runs daily at 05:20 UTC (change if you like)
  workflow_dispatch:        # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # needed to push commits

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run updater
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_TAG:  ${{ secrets.CLOUDFLARE_ZONE_TAG }}
          TARGET_FILE:          data/cloudflare_uniques.json
          UPDATE_README:        "true"   # set to "false" to skip README edits
          GITHUB_TOKEN:         ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_cf_uniques.py
          
      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(stats): update Cloudflare unique visitors"
            git push
          else
            echo "No changes to commit."
          fi
